name: Project Checkup

on:
  pull_request:
    branches: ['main']
  workflow_dispatch:

jobs:
  checkup:
    name: 'checkup'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: npm ci
      - run: npx nx affected --target=test --base=remotes/origin/main --parallel
      - run: npx nx affected --target=lint --base=remotes/origin/main --parallel -- --max-warnings 0
      - run: npx nx affected --target=build --base=remotes/origin/main --parallel --prod
