name: Deploy Prod

on:
  push:
    branches: ['prod']
  workflow_dispatch:

jobs:
  migrations:
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run migrations:run
        env:
          NX_DB_HOST: ${{ secrets.DB_HOST }}
          NX_DB_USER: ${{ secrets.DB_USER }}
          NX_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          NX_DB_PORT: ${{ secrets.DB_PORT }}
          NX_DB_NAME: ${{ secrets.DB_NAME }}
  build:
    runs-on: ubuntu-latest
    needs: migrations
    environment:
      name: prod
      url: https://dialoq-dd3791188bd4.herokuapp.com/
    steps:
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_MAIL}}
          branch: prod
